package com.dataaccess.webservicesserver;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.11.redhat-00001
 * 2020-10-04T22:55:40.291-03:00
 * Generated source version: 3.2.11.redhat-00001
 *
 */
@WebService(targetNamespace = "http://www.dataaccess.com/webservicesserver/", name = "TextCasingSoapType")
@XmlSeeAlso({ObjectFactory.class})
public interface TextCasingSoapType {

    /**
     * Change string to uppercase adding token between characters of each word.
     */
    @WebMethod(operationName = "UppercaseWordsWithToken")
    @RequestWrapper(localName = "UppercaseWordsWithToken", targetNamespace = "http://www.dataaccess.com/webservicesserver/", className = "com.dataaccess.webservicesserver.UppercaseWordsWithToken")
    @ResponseWrapper(localName = "UppercaseWordsWithTokenResponse", targetNamespace = "http://www.dataaccess.com/webservicesserver/", className = "com.dataaccess.webservicesserver.UppercaseWordsWithTokenResponse")
    @WebResult(name = "UppercaseWordsWithTokenResult", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
    public java.lang.String uppercaseWordsWithToken(
        @WebParam(name = "sAString", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
        java.lang.String sAString,
        @WebParam(name = "sToken", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
        java.lang.String sToken
    );

    /**
     * Uppercase letters that are lowercase and lowercase letters that are uppercase.
     */
    @WebMethod(operationName = "InvertStringCase")
    @RequestWrapper(localName = "InvertStringCase", targetNamespace = "http://www.dataaccess.com/webservicesserver/", className = "com.dataaccess.webservicesserver.InvertStringCase")
    @ResponseWrapper(localName = "InvertStringCaseResponse", targetNamespace = "http://www.dataaccess.com/webservicesserver/", className = "com.dataaccess.webservicesserver.InvertStringCaseResponse")
    @WebResult(name = "InvertStringCaseResult", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
    public java.lang.String invertStringCase(
        @WebParam(name = "sAString", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
        java.lang.String sAString
    );

    /**
     * Invert the casing of the first letter and adjust the string to conform with the current casing of first letter.
     */
    @WebMethod(operationName = "InvertCaseFirstAdjustStringToCurrent")
    @RequestWrapper(localName = "InvertCaseFirstAdjustStringToCurrent", targetNamespace = "http://www.dataaccess.com/webservicesserver/", className = "com.dataaccess.webservicesserver.InvertCaseFirstAdjustStringToCurrent")
    @ResponseWrapper(localName = "InvertCaseFirstAdjustStringToCurrentResponse", targetNamespace = "http://www.dataaccess.com/webservicesserver/", className = "com.dataaccess.webservicesserver.InvertCaseFirstAdjustStringToCurrentResponse")
    @WebResult(name = "InvertCaseFirstAdjustStringToCurrentResult", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
    public java.lang.String invertCaseFirstAdjustStringToCurrent(
        @WebParam(name = "sAString", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
        java.lang.String sAString
    );

    @WebMethod(operationName = "TitleCaseWordsWithToken")
    @RequestWrapper(localName = "TitleCaseWordsWithToken", targetNamespace = "http://www.dataaccess.com/webservicesserver/", className = "com.dataaccess.webservicesserver.TitleCaseWordsWithToken")
    @ResponseWrapper(localName = "TitleCaseWordsWithTokenResponse", targetNamespace = "http://www.dataaccess.com/webservicesserver/", className = "com.dataaccess.webservicesserver.TitleCaseWordsWithTokenResponse")
    @WebResult(name = "TitleCaseWordsWithTokenResult", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
    public java.lang.String titleCaseWordsWithToken(
        @WebParam(name = "sText", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
        java.lang.String sText,
        @WebParam(name = "sToken", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
        java.lang.String sToken
    );

    /**
     * Change string to lowercase adding token between characters of each word.
     */
    @WebMethod(operationName = "LowercaseWordsWithToken")
    @RequestWrapper(localName = "LowercaseWordsWithToken", targetNamespace = "http://www.dataaccess.com/webservicesserver/", className = "com.dataaccess.webservicesserver.LowercaseWordsWithToken")
    @ResponseWrapper(localName = "LowercaseWordsWithTokenResponse", targetNamespace = "http://www.dataaccess.com/webservicesserver/", className = "com.dataaccess.webservicesserver.LowercaseWordsWithTokenResponse")
    @WebResult(name = "LowercaseWordsWithTokenResult", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
    public java.lang.String lowercaseWordsWithToken(
        @WebParam(name = "sAString", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
        java.lang.String sAString,
        @WebParam(name = "sToken", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
        java.lang.String sToken
    );

    /**
     * Invert the casing of the first letter and adjust the string to conform with the previous casing of first letter.
     */
    @WebMethod(operationName = "InvertCaseFirstAdjustStringToPrevious")
    @RequestWrapper(localName = "InvertCaseFirstAdjustStringToPrevious", targetNamespace = "http://www.dataaccess.com/webservicesserver/", className = "com.dataaccess.webservicesserver.InvertCaseFirstAdjustStringToPrevious")
    @ResponseWrapper(localName = "InvertCaseFirstAdjustStringToPreviousResponse", targetNamespace = "http://www.dataaccess.com/webservicesserver/", className = "com.dataaccess.webservicesserver.InvertCaseFirstAdjustStringToPreviousResponse")
    @WebResult(name = "InvertCaseFirstAdjustStringToPreviousResult", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
    public java.lang.String invertCaseFirstAdjustStringToPrevious(
        @WebParam(name = "sAString", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
        java.lang.String sAString
    );

    /**
     * Change string to uppercase adding token between characters.
     */
    @WebMethod(operationName = "AllUppercaseWithToken")
    @RequestWrapper(localName = "AllUppercaseWithToken", targetNamespace = "http://www.dataaccess.com/webservicesserver/", className = "com.dataaccess.webservicesserver.AllUppercaseWithToken")
    @ResponseWrapper(localName = "AllUppercaseWithTokenResponse", targetNamespace = "http://www.dataaccess.com/webservicesserver/", className = "com.dataaccess.webservicesserver.AllUppercaseWithTokenResponse")
    @WebResult(name = "AllUppercaseWithTokenResult", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
    public java.lang.String allUppercaseWithToken(
        @WebParam(name = "sAString", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
        java.lang.String sAString,
        @WebParam(name = "sToken", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
        java.lang.String sToken
    );

    /**
     * Change string to lowercase adding token between characters.
     */
    @WebMethod(operationName = "AllLowercaseWithToken")
    @RequestWrapper(localName = "AllLowercaseWithToken", targetNamespace = "http://www.dataaccess.com/webservicesserver/", className = "com.dataaccess.webservicesserver.AllLowercaseWithToken")
    @ResponseWrapper(localName = "AllLowercaseWithTokenResponse", targetNamespace = "http://www.dataaccess.com/webservicesserver/", className = "com.dataaccess.webservicesserver.AllLowercaseWithTokenResponse")
    @WebResult(name = "AllLowercaseWithTokenResult", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
    public java.lang.String allLowercaseWithToken(
        @WebParam(name = "sAString", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
        java.lang.String sAString,
        @WebParam(name = "sToken", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
        java.lang.String sToken
    );
}
